document.write('			<div id="right">');
document.write('				<p>');
document.write('					<span class="bold"><a href="criteria.html">Grants are available to anyone who meets the criteria of the Trust.</a></span>');
document.write('				</p>');
document.write('				<p class="italic">');
document.write('					If you would like further details, ');
document.write('					<br />or an application form,'); 
document.write('					<br />please contact:<br />');
document.write('					<span class="bold">');
document.write('					The GPM Charitable Trust<br />');
document.write('					c/o 43 Spriggs Close<br />');
document.write('					Clapham <br />');
document.write('					Bedford <br />');
document.write('					MK41 6GD</span>');
document.write('				<p>');
document.write('				<p class="italic">');
document.write('					telephone<br />');
document.write('					<span class="bold">07733 262991</span>');
document.write('				</p>');
document.write('				<p class="italic">');
document.write('					email<br />');
document.write('					<span class="bold"><a href="mailto:keithkeys17@gmail.com">keithkeys17@gmail.com</a></span>');
document.write('				</p>');
document.write('				<p class="italic">');
document.write('					or download the application form<br />');
document.write('					<span class="bold"><a href="docs/gpmtrustappform.pdf" target="_blank">GPM Charitable Trust ');
document.write('					Application Form</a></span>');
document.write('				</p>');
document.write('				<p class="italic_small">					');
document.write('					You can then fill in the form on your ');
document.write('					computer, save and return it by email,'); 
document.write('					or print out the form, complete and ');
document.write('					return it by post.<br />');
document.write('					You will need Acrobat Reader to open ');
document.write('					the form if it is not already installed on ');
document.write('					your computer. Click on the link for the free download<br /><br />');
document.write('					<a href="http://get.adobe.com/uk/reader/" target="_blank"><img src="images/getacro.gif" width="88" height="31" border="0" /></a>');
document.write('				</p>');
document.write('				<p class="small">Registered Charity No 227177</p>');
document.write('			</div>');